name: diff-data
on: workflow_dispatch
jobs:
  diff-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: lts/*

      - name: Install depencencies
        run: |
          npm install

      - name: Diff data
        run: |
          node diff-node-wrapper.js

      - name: Upload diff
        uses: actions/upload-artifact@v3
        with:
          path: build/*.json
